# 默认以下配置默认会读取环境变量的值
mysql-host: ${MYSQL_HOST:172.18.0.3}
mysql-port: ${MYSQL_PORT:3306}
mysql-username: ${MYSQL_USERNAME:root}
mysql-password: ${MYSQL_PASSWORD:"aoki123456"}

# redis配置
redis-host: ${REDIS_HOST:172.20.0.2}
redis-port: ${REDIS_PORT:6379}
redis-password: ${REDIS_PASSWORD:"aoki123456"}

mail-username: ${MAIL_USERNAME:your_mail_username}
mail-password: ${MAIL_PASSWORD:your_mail_password}
mail-host: ${MAIL_HOST:smtp.qq.com}
mail-port: ${MAIL_PORT:465}


# 服务端口号
server:
  port: 8080

spring:
  datasource: # 数据库配置
    url: jdbc:mysql://${mysql-host}:${mysql-port}/aoki?characterEncoding=utf-8&useSSL=false&rewriteBatchedStatements=true&&allowPublicKeyRetrieval=true
    username: ${mysql-username}
    password: ${mysql-password}
  data:                       #直接连接redis
    redis:
      host: ${redis-host}         # 地址
      port: ${redis-port}              # 端口
      password: ${redis-password}        # 密码
      connect-timeout: 30s
      timeout: 30s

  mail: #邮件配置
    username: ${mail-username}
    password: ${mail-password}
    host: ${mail-host}
    port: ${mail-port}
