# 默认以下配置默认会读取环境变量的值
mysql-public-host: localhost
mysql-public-port: 6603
mysql-username: root
mysql-password: "040110"

redis-host: localhost
redis-port: 6379
redis-password: 040110


# 服务端口号
server:
  port: 8080

spring:
  datasource: # 数据库配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${mysql-public-host}:${mysql-public-port}/aoki?characterEncoding=utf-8&useSSL=false&rewriteBatchedStatements=true&&allowPublicKeyRetrieval=true
    username: ${mysql-username}
    password: ${mysql-password}
  data:                       #直接连接redis
    redis:
      host: ${redis-host}         # 地址
      port: ${redis-port}              # 端口
      password: ${redis-password}        # 密码
  cache:
    type: redis               # 缓存使用redis
    redis:
      time-to-live: 1800      # 缓存过期时间，单位 s
      cache-null-values: true   # 是否缓存空值

#&serverTimezone=GMT
logging:
  file:
    path: ./aoki_backend
  level:
    root: info
  config: classpath:logback-spring.xml
