# 默认以下配置默认会读取环境变量的值
mysql-host: localhost
mysql-port: 3306
mysql-username: root
mysql-password: "aoki123456"

redis-host: localhost
redis-port: 6379
redis-password: "aoki123456"

mail-username: 2701679328@qq.com
mail-password: habozfhkpjgsdfjg
mail-host: smtp.qq.com
mail-port: 465

# 服务端口号
server:
  port: 8080

spring:
  datasource: # 数据库配置
    url: jdbc:mysql://${mysql-host}:${mysql-port}/aoki?characterEncoding=utf-8&useSSL=false&rewriteBatchedStatements=true&&allowPublicKeyRetrieval=true
    username: ${mysql-username}
    password: ${mysql-password}
  data:                       #直接连接redis
    redis:
      host: ${redis-host}         # 地址
      port: ${redis-port}              # 端口
      password: ${redis-password}        # 密码
      connect-timeout: 30s
      timeout: 30s


  mail:     #邮件配置
    username: ${mail-username}
    password: ${mail-password}
    host: ${mail-host}
    port: ${mail-port}
